---
abstract: 'Interface to Google Diacritize API.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTTP::Request: 1.40
  JSON: 2.15
  LWP::UserAgent: 2.33
  Readonly: 1.03
  Test::More: 0
  URI::Escape: 3.29
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-Diacritize
provides:
  WWW::Google::Diacritize:
    file: lib/WWW/Google/Diacritize.pm
    version: 0.07
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
